name: "Setup Dependencies"
description: "Install system dependencies (OpenCV, GStreamer, pkg-config) for pup project"
inputs:
  os:
    description: "Operating system"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install system dependencies (Ubuntu)
      if: startsWith(inputs.os, 'ubuntu')
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          pkg-config \
          cmake \
          libglib2.0-dev \
          libgstreamer1.0-dev \
          libgstreamer-plugins-base1.0-dev \
          libgstreamer-plugins-bad1.0-dev \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good \
          gstreamer1.0-plugins-bad \
          gstreamer1.0-plugins-ugly \
          libopencv-dev \
          clang \
          libclang-dev \
          libomp-dev

    - name: Install system dependencies (macOS)
      if: startsWith(inputs.os, 'macos')
      shell: bash
      run: |
        brew update
        brew install \
          cmake \
          pkg-config \
          glib \
          gstreamer \
          gst-plugins-base \
          gst-plugins-good \
          gst-plugins-bad \
          gst-plugins-ugly \
          opencv \
          libomp

        # Set environment variables for linking
        echo "PKG_CONFIG_PATH=$(brew --prefix)/lib/pkgconfig:${PKG_CONFIG_PATH}" >> $GITHUB_ENV
        echo "DYLD_FALLBACK_LIBRARY_PATH=$(xcode-select --print-path)/usr/lib/" >> $GITHUB_ENV
