[package]
name = "pup"
version = "0.1.0"
edition = "2021"

[target.'cfg(target_vendor= "apple")'.dependencies]
[dependencies]
anyhow = "1.0.79"
candle = { git = "https://github.com/huggingface/candle.git", version = "0.6.0", features = ["metal"], package = "candle-core"}
candle-nn = { git = "https://github.com/huggingface/candle.git", version = "0.6.0" }
candle-onnx = { git = "https://github.com/huggingface/candle.git", version = "0.6.0" }
candle-transformers = { git = "https://github.com/huggingface/candle.git", version = "0.6.0" }
clap = { features = ["derive"], version = "4.4.18" }
image = { version = "0.24.7", default-features = false, features = ["jpeg", "png"] }
imageproc = { version = "0.23.0", default-features = false }
hf-hub = "0.3.2"
serde = "1.0.196"
serde_json = "1.0.113"
tracing = "0.1.37"
tracing-chrome = "0.7.1"
tracing-subscriber = "0.3.7"
rusttype = "0.9.3"
mat2image = { git = "https://github.com/rcastill/mat2image.git", rev = "f222cb14"}
# mat2image = { git = "https://github.com/rcastill/mat2image.git"}
openssl = { version = "0.10", features = ["vendored"] }
opencv = "=0.88.8"
