[package]
edition = "2021"
name = "pup"
version = "0.2.0"

[target.'cfg(target_vendor= "apple")'.dependencies]
[dependencies]
clap = { version = "4", features = ["derive"] }
gstreamer = "0.23.4"
gstreamer-video = "0.23.4"
gstreamer-app = "0.23.4"
ort = { version = "2.0.0-rc.9" }
ndarray = "0.15"
anyhow = "1.0"
cairo-rs = "0.16"

[profile.release]
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
lto = true          # Enable Link Time Optimization
opt-level = "z"     # Optimize for size.
panic = "abort"     # Abort on panic
strip = true        # Automatically strip symbols from the binary.
