[package]
edition = "2021"
name = "pup"
version = "0.1.0"

[target.'cfg(target_vendor= "apple")'.dependencies]
[dependencies]
anyhow = "1.0.79"
candle = { git = "https://github.com/huggingface/candle.git", version = "0.6.0", features = ["metal"], package = "candle-core"}
candle-nn = { git = "https://github.com/huggingface/candle.git", version = "0.6.0", features = ["metal"]}
candle-onnx = { git = "https://github.com/huggingface/candle.git", version = "0.6.0"}
candle-transformers = { git = "https://github.com/huggingface/candle.git", version = "0.6.0", features = ["metal"]}
clap = { features = ["derive"], version = "4.4.18" }
hf-hub = "0.3.2"
image = { version = "0.24.7", default-features = false, features = ["jpeg", "png"] }
imageproc = { version = "0.23.0", default-features = false }
opencv = "0.92.0"
openssl = { version = "0.10", features = ["vendored"] }
rusttype = "0.9.3"
serde = "1.0.196"
serde_json = "1.0.113"
tracing = "0.1.37"
tracing-chrome = "0.7.1"
tracing-subscriber = "0.3.7"

[profile.release]
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
lto = true          # Enable Link Time Optimization
opt-level = "z"     # Optimize for size.
panic = "abort"     # Abort on panic
strip = true        # Automatically strip symbols from the binary.
