[package]
edition = "2021"
name = "pup"
version = "0.2.0"

[target.'cfg(target_vendor= "apple")'.dependencies]
[dependencies]
clap = { version = "4", features = ["derive"] }
gstreamer = "0.21"
gstreamer-video = "0.21"
gstreamer-app = "0.21"
ort = { version = "2.0.0-rc.9" , features = ["load-dynamic"] }
ndarray = "0.15"
anyhow = "1.0"

[profile.release]
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
lto = true          # Enable Link Time Optimization
opt-level = "z"     # Optimize for size.
panic = "abort"     # Abort on panic
strip = true        # Automatically strip symbols from the binary.
