# Sample Video Detection Only (Terminal Output)
# Usage: cargo run --release -- --config configs/sample_video_detection.toml

[mode]
type = "detection"

[input]
source = "assets/sample.mp4"

[inference]
backend = "ort"
execution_providers = ["coreml", "cpu"]
model_path = "models/yolov8n.onnx"
confidence_threshold = 0.5
batch_size = 1

[output]
display_enabled = false
recording_enabled = false
output_format = "json"

[preprocessing]
target_size = [640, 640]
letterbox = true
normalize = true