name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build ${{ matrix.platform }} with Rust ${{ matrix.toolchain }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest]
        toolchain: [stable]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Setup dependencies
        uses: ./.github/actions/setup-dependencies
        with:
          os: ${{ matrix.platform }}

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: build-${{ matrix.platform }}-${{ matrix.toolchain }}
          cache-targets: true
          cache-all-crates: true

      - name: Build (Debug)
        run: cargo build

      - name: Build (Release)
        run: cargo build --release

      - name: Build all binaries
        run: cargo build --release --bins
