name: Python

on:
  push:
    branches: [main, master]
    paths:
      - "**.py"
      - "**.rs"
      - "pyproject.toml"
      - ".github/workflows/python.yml"
      - ".github/actions/**"
  pull_request:
    paths:
      - "**.py"
      - "**.rs"
      - "pyproject.toml"
      - ".github/workflows/python.yml"
      - ".github/actions/**"
  workflow_dispatch:

jobs:
  python-tests:
    name: Python ${{ matrix.python-version }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: python-test-${{ matrix.os }}-${{ matrix.python-version }}

      - name: Setup dependencies
        uses: ./.github/actions/setup-dependencies
        with:
          python-version: ${{ matrix.python-version }}
          enable-python: "true"
          os: ${{ matrix.os }}

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Python dependencies
        run: |
          source .venv/bin/activate
          uv pip install -e ".[dev]" || uv pip install -e .

      - name: Run Python tests
        run: |
          source .venv/bin/activate
          if [ -d "tests" ] && find tests -name "test_*.py" | grep -q .; then
            uv run pytest tests/ -v --tb=short
          else
            echo "No Python tests found, skipping test execution"
          fi

      - name: Run code formatting checks
        run: |
          source .venv/bin/activate
          uv run black --check python/ || echo "Black not configured"
          uv run ruff check python/ || echo "Ruff not configured"

      - name: Test Python module import
        run: |
          source .venv/bin/activate
          python -c "import pup; print('Pup module imported successfully')" || echo "Module import test skipped"
