name: Rust

on:
  push:
    branches: [main, master]
    paths:
      - "**.rs"
      - "Cargo.toml"
      - "Cargo.lock"
      - "build.rs"
      - ".github/workflows/rust.yml"
      - ".github/actions/**"
  pull_request:
    paths:
      - "**.rs"
      - "Cargo.toml"
      - "Cargo.lock"
      - "build.rs"
      - ".github/workflows/rust.yml"
      - ".github/actions/**"
  workflow_dispatch:

jobs:
  rust-check:
    name: Rust Check
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Setup dependencies
        uses: ./.github/actions/setup-dependencies
        with:
          os: ${{ matrix.os }}

      - name: Fix macOS linker configuration
        if: startsWith(matrix.os, 'macos')
        run: |
          # Disable the problematic -fuse-ld flag that causes issues with Xcode-beta
          echo "RUSTFLAGS=-C link-arg=-Wl,-ld_classic" >> $GITHUB_ENV

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.os }}
          cache-targets: true
          cache-all-crates: true

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --bins --lib -- -D warnings

      - name: Cargo check
        run: cargo check --all

      - name: Cargo build
        run: cargo build --release

      - name: Run tests
        run: cargo test
